version: '3'

services:
  mina-local-network:
    restart: no
    image: o1js-build
    build: .
    privileged: true
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    command: "bash -x /app/run-all-tests.sh"
    # strace -f -o /tmp/strace.txt
