version: '3'

services:
  mina-local-network:
    restart: no
    image: o1js-build
    build: .
    privileged: true
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    command: "bash -x /app/run-all-tests.sh"

  perf-reporting:
    restart: no
    image: perf-reporting
    build: perf-reporting
    volumes:
      - perf.data.zip:/app/perf-reporting/perf.data.zip
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    command: "bash -x /app/perf/reporting/perf-report.sh"
