version: '3'

services:
  mina-local-network:
    restart: no
    image: o1js-build
    build: .
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    cap_add:
      - SYS_PTRACE
    command: "strace -f -o /tmp/strace.txt pnpm run test"