version: '3'

services:
  mina-local-network:
    restart: no
    image: o1js-build
    build: .
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    cap_add:
      - SYS_PTRACE
    command: "pnpm run test"
    # strace -f -o /tmp/strace.txt
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
networks:
  localprom:
    driver: bridge
