version: '3'

services:
  mina-local-network:
    restart: no
    image: o1js-build
    build: .
    privileged: true
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
    working_dir: /app
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    command: "bash -x /app/run-all-tests.sh"

  reporting:
    restart: no
    image: perf-reporting
    build:
      dockerfile: perf-reporting/Dockerfile.simple
#      dockerfile: perf-reporting/Dockerfile
      
    volumes:
      - type: bind
        source: "/home/runner/work/o1js/o1js/data/"
        target: "/app/perf-reporting/data/"
        
    environment:
      - PROOF_LEVEL=full
      - LOG_LEVEL=Debug
      - WORKSPACE_DIR=$WORKSPACE_DIR

    working_dir: /app
    
    command: "bash -x /app/perf/reporting/perf-report.sh"
