name: Docker Image CI

on:
  repository_dispatch:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: meta-introspector/checkout@v4
      with: 
        submodules: recursive
    
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image via docker compose
      run: docker compose build 
    - name: run the Docker tests
      run: docker compose up
    - name: docker cp results
      run: docker compose cp mina-local-network:/tmp/perf.data perf.data
    #- name: list files docker
    #  run: docker compose run mina-local-network /bin/find /app/.clinic/
    #- name: docker cp strace.txt
    #  run: docker compose cp mina-local-network:/app/.clinic clinic
    #- name: list files
    #  run: find clinic

    - name: Archive results
      uses: meta-introspector/upload-artifact@v4
      with:
           name: perf.data
           path: perf.data
