name: process_perf
on:
  workflow_dispatch: null
  push:
    branches:
      - test-perf
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@v4
        #with:
        #  submodules: recursive
      - name: Login to GHCR
        uses: meta-introspector/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: pull the image
        run: docker pull ghcr.io/meta-introspector/o1js/o1js-perf-recording:latest
      - name: Download a Build Artifact
        uses: meta-introspector/action-download-artifact@v6
        with:
          workflow_search: true
          commit: 1ea14294b4a7a051ba0872de559658164d0aaae8
          skip_unpack: true
          path: data
      - name: run the report
        run: docker compose up --build reporting-github
        env:
          WORKSPACE_DIR2: $GITHUB_WORKSPACE
          WORKSPACE_DIR: $GITHUB_WORKSPACE

      - name: run the report
        run: docker compose up --build reporting-github
        env:
          WORKSPACE_DIR2: $GITHUB_WORKSPACE
          WORKSPACE_DIR: $GITHUB_WORKSPACE
      - name: Archive results
        uses: meta-introspector/upload-artifact@v4
        with:
           name: results.tgz
           path: perf-reporting/output/results.tgz
