name: process_perf
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Download a Build Artifact
        uses: meta-introspector/action-download-artifact@v6
        with:
          workflow_search: true
          commit: 584fd53a9f50126360ab764537f4ae10bd5e3666
          skip_unpack: true
      # now run docker
      # mount the data into the container
    
