name: Build and Publish Current Branch Docker image
on:
  workflow_dispatch:
  push:
    branches: [ "build-image" ]
  pull_request:
    branches: [ "build-image" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: meta-introspector/checkout@v4
      with: 
        submodules: recursive     
    - name: Build and Publish Docker image test
      uses: meta-introspector/docker-bpgpr@1.0.0
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        image_name: o1js-perf-recording
        tag_with_ref: true        
        tags: ${{ github.ref_name }}
        dockerfile: Dockerfile
