name: run Perf Test and collect data
env:
  default_image: "ghcr.io/meta-introspector/o1js/o1js-perf-recording:latest"
  container_name: "mixed-source"
on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Docker url to execute'
        #default: "ghcr.io/meta-introspector/o1js/o1js-perf-recording:5ce0221662cecbca9a3de05601af94a15b154a3bcf8bafcb0cfa1f5b9f407bdc"
        default: "ghcr.io/meta-introspector/o1js/o1js-perf-recording:latest"
  push:
    branches: [ "feature/just_test" ]
  pull_request:
    branches: [ "collect-perf" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: meta-introspector/checkout@v4
      #with: 
      #  submodules: recursive
      
    - name: Login to GHCR
      uses: meta-introspector/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: pull the image
      run: docker pull ${{ inputs.image_url || env.default_image }}
      
    - name: run the Docker tests
      run: docker compose up ${{ env.container_name }}
      env:
        DOCKER_IMAGE_URL: ${{ inputs.image_url || env.default_image}}         
      
    - name: docker cp results
      run: docker compose cp ${{ env.container_name }}:/tmp/perf.data.tar.gz perf.data.tar.gz

    - name: Archive results
      uses: meta-introspector/upload-artifact@v4
      with:
           name: perf.data.tar.gz
           path: perf.data.tar.gz
