name: run Perf Test and collect data
env:
  DOCKER_IMAGE_URL: "ghcr.io/meta-introspector/o1js/o1js-perf-recording:sha256:5ce0221662cecbca9a3de05601af94a15b154a3bcf8bafcb0cfa1f5b9f407bdc"
on:
  workflow_dispatch:
  push:
    branches: [ "collect-perf" ]
  pull_request:
    branches: [ "collect-perf" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: meta-introspector/checkout@v4
      #with: 
      #  submodules: recursive
      
    - name: Login to GHCR
      uses: meta-introspector/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: pull the image
      run: docker pull ${DOCKER_IMAGE_URL}
      
    - name: run the Docker tests
      run: docker compose up mina-local-network
      env:
        DOCKER_IMAGE_URL: ${DOCKER_IMAGE_URL}       
      
    - name: docker cp results
      run: docker compose cp mina-local-network:/tmp/perf.data.tar.gz perf.data.tar.gz

    - name: Archive results
      uses: meta-introspector/upload-artifact@v4
      with:
           name: perf.data.tar.gz
           path: perf.data.tar.gz
